# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'geometry_helper.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import PyQt5

from PyQt5 import QtCore, QtGui, QtWidgets
import shapes as s
if hasattr(QtCore.Qt, 'AA_EnableHighDpiScaling'):
    PyQt5.QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)

if hasattr(QtCore.Qt, 'AA_UseHighDpiPixmaps'):
    PyQt5.QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_UseHighDpiPixmaps, True)
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(509, 600)
        MainWindow.setMinimumSize(QtCore.QSize(509, 600))
        MainWindow.setMaximumSize(QtCore.QSize(509, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 571))
        self.tabWidget.setObjectName("tabWidget")
        self.circle_tab = QtWidgets.QWidget()
        self.circle_tab.setObjectName("circle_tab")
        self.label = QtWidgets.QLabel(self.circle_tab)
        self.label.setGeometry(QtCore.QRect(70, 80, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.radius = QtWidgets.QLineEdit(self.circle_tab)
        self.radius.setGeometry(QtCore.QRect(230, 80, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radius.setFont(font)
        self.radius.setObjectName("radius")
        self.answer_section = QtWidgets.QLabel(self.circle_tab)
        self.answer_section.setGeometry(QtCore.QRect(70, 200, 361, 231))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.answer_section.setFont(font)
        self.answer_section.setWordWrap(True)
        self.answer_section.setObjectName("answer_section")
        self.submit_button = QtWidgets.QPushButton(self.circle_tab)
        self.submit_button.setGeometry(QtCore.QRect(70, 460, 84, 25))
        self.submit_button.setObjectName("submit_button")
        self.submit_button.clicked.connect(self.submit_circle)
        self.clear_button = QtWidgets.QPushButton(self.circle_tab)
        self.clear_button.setGeometry(QtCore.QRect(360, 460, 84, 25))
        self.clear_button.setObjectName("clear_button")
        self.clear_button.clicked.connect(self.clear_circle)
        self.tabWidget.addTab(self.circle_tab, "")
        self.elipse_tab = QtWidgets.QWidget()
        self.elipse_tab.setObjectName("elipse_tab")
        self.label_2 = QtWidgets.QLabel(self.elipse_tab)
        self.label_2.setGeometry(QtCore.QRect(50, 60, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.elipse_tab)
        self.label_3.setGeometry(QtCore.QRect(50, 130, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.minor_axis = QtWidgets.QLineEdit(self.elipse_tab)
        self.minor_axis.setGeometry(QtCore.QRect(240, 60, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.minor_axis.setFont(font)
        self.minor_axis.setObjectName("minor_axis")
        self.major_axis = QtWidgets.QLineEdit(self.elipse_tab)
        self.major_axis.setGeometry(QtCore.QRect(240, 130, 161, 21))
        self.major_axis.setObjectName("major_axis")
        self.answer_section2 = QtWidgets.QLabel(self.elipse_tab)
        self.answer_section2.setGeometry(QtCore.QRect(80, 240, 321, 161))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.answer_section2.setFont(font)
        self.answer_section2.setWordWrap(True)
        self.answer_section2.setObjectName("answer_section2")
        self.submit_button2 = QtWidgets.QPushButton(self.elipse_tab)
        self.submit_button2.setGeometry(QtCore.QRect(70, 460, 84, 25))
        self.submit_button2.setObjectName("submit_button2")
        self.submit_button2.clicked.connect(self.submit_elipse)
        self.clear_button2 = QtWidgets.QPushButton(self.elipse_tab)
        self.clear_button2.setGeometry(QtCore.QRect(360, 460, 84, 25))
        self.clear_button2.setObjectName("clear_button2")
        self.clear_button2.clicked.connect(self.clear_elipse)
        self.tabWidget.addTab(self.elipse_tab, "")
        self.triangle_tab = QtWidgets.QWidget()
        self.triangle_tab.setObjectName("triangle_tab")
        self.label_5 = QtWidgets.QLabel(self.triangle_tab)
        self.label_5.setGeometry(QtCore.QRect(60, 50, 52, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.triangle_tab)
        self.label_6.setGeometry(QtCore.QRect(60, 90, 52, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.triangle_tab)
        self.label_7.setGeometry(QtCore.QRect(60, 130, 52, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.triangle_tab)
        self.label_8.setGeometry(QtCore.QRect(280, 50, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.triangle_tab)
        self.label_9.setGeometry(QtCore.QRect(280, 90, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.triangle_tab)
        self.label_10.setGeometry(QtCore.QRect(280, 130, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.submit_button3 = QtWidgets.QPushButton(self.triangle_tab)
        self.submit_button3.setGeometry(QtCore.QRect(70, 460, 84, 25))
        self.submit_button3.setObjectName("submit_button3")
        self.submit_button3.clicked.connect(self.submit_triangle)
        self.clear_button3 = QtWidgets.QPushButton(self.triangle_tab)
        self.clear_button3.setGeometry(QtCore.QRect(360, 460, 84, 25))
        self.clear_button3.setObjectName("clear_button3")
        self.clear_button3.clicked.connect(self.clear_triangle)
        self.label_11 = QtWidgets.QLabel(self.triangle_tab)
        self.label_11.setGeometry(QtCore.QRect(71, 254, 371, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(False)
        self.label_11.setFont(font)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.side1 = QtWidgets.QLineEdit(self.triangle_tab)
        self.side1.setGeometry(QtCore.QRect(140, 50, 104, 21))
        self.side1.setObjectName("side1")
        self.side2 = QtWidgets.QLineEdit(self.triangle_tab)
        self.side2.setGeometry(QtCore.QRect(140, 90, 104, 21))
        
        self.side2.setObjectName("side2")
        self.side3 = QtWidgets.QLineEdit(self.triangle_tab)
        self.side3.setGeometry(QtCore.QRect(140, 130, 104, 21))
        self.side3.setObjectName("side3")
        self.angle1 = QtWidgets.QLineEdit(self.triangle_tab)
        self.angle1.setGeometry(QtCore.QRect(380, 50, 104, 21))
        self.angle1.setObjectName("angle1")
        self.angle2 = QtWidgets.QLineEdit(self.triangle_tab)
        self.angle2.setGeometry(QtCore.QRect(380, 90, 104, 21))
        self.angle2.setObjectName("angle2")
        self.angle3 = QtWidgets.QLineEdit(self.triangle_tab)
        self.angle3.setGeometry(QtCore.QRect(380, 130, 104, 21))
        self.angle3.setObjectName("angle3")
        self.tabWidget.addTab(self.triangle_tab, "")
        self.square_tab = QtWidgets.QWidget()
        self.square_tab.setObjectName("square_tab")
        self.submit_button4 = QtWidgets.QPushButton(self.square_tab)
        self.submit_button4.setGeometry(QtCore.QRect(70, 460, 84, 25))
        self.submit_button4.setObjectName("submit_button4")
        self.submit_button4.clicked.connect(self.submit_square)
        self.clear_button4 = QtWidgets.QPushButton(self.square_tab)
        self.clear_button4.setGeometry(QtCore.QRect(360, 460, 84, 25))
        self.clear_button4.setObjectName("clear_button4")
        self.clear_button4.clicked.connect(self.clear_square)
        self.label_12 = QtWidgets.QLabel(self.square_tab)
        self.label_12.setGeometry(QtCore.QRect(90, 100, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.square_side = QtWidgets.QLineEdit(self.square_tab)
        self.square_side.setGeometry(QtCore.QRect(230, 110, 141, 21))
        self.square_side.setObjectName("square_side")
        self.answer_section4 = QtWidgets.QLabel(self.square_tab)
        self.answer_section4.setGeometry(QtCore.QRect(70, 220, 371, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.answer_section4.setFont(font)
        self.answer_section4.setWordWrap(True)
        self.answer_section4.setObjectName("answer_section4")
        self.tabWidget.addTab(self.square_tab, "")
        self.rectangle_tab = QtWidgets.QWidget()
        self.rectangle_tab.setObjectName("rectangle_tab")
        self.label_4 = QtWidgets.QLabel(self.rectangle_tab)
        self.label_4.setGeometry(QtCore.QRect(90, 70, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_13 = QtWidgets.QLabel(self.rectangle_tab)
        self.label_13.setGeometry(QtCore.QRect(90, 120, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.rectangle_side1 = QtWidgets.QLineEdit(self.rectangle_tab)
        self.rectangle_side1.setGeometry(QtCore.QRect(243, 70, 141, 21))
        self.rectangle_side1.setObjectName("rectangle_side1")
        self.rectangle_side2 = QtWidgets.QLineEdit(self.rectangle_tab)
        self.rectangle_side2.setGeometry(QtCore.QRect(243, 120, 141, 21))
        self.rectangle_side2.setObjectName("rectangle_side2")
        self.answer_section5 = QtWidgets.QLabel(self.rectangle_tab)
        self.answer_section5.setGeometry(QtCore.QRect(70, 240, 311, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.answer_section5.setFont(font)
        self.answer_section5.setWordWrap(True)
        self.answer_section5.setObjectName("answer_section5")
        self.submit_button5 = QtWidgets.QPushButton(self.rectangle_tab)
        self.submit_button5.setGeometry(QtCore.QRect(70, 460, 84, 25))
        self.submit_button5.setObjectName("submit_button5")
        self.submit_button5.clicked.connect(self.submit_rectangle)
        self.clear_button5 = QtWidgets.QPushButton(self.rectangle_tab)
        self.clear_button5.setGeometry(QtCore.QRect(360, 460, 84, 25))
        self.clear_button5.setObjectName("clear_button5")
        self.clear_button5.clicked.connect(self.clear_rectangle)
        self.tabWidget.addTab(self.rectangle_tab, "")
        self.trapezoid_tab = QtWidgets.QWidget()
        self.trapezoid_tab.setObjectName("trapezoid_tab")
        self.label_15 = QtWidgets.QLabel(self.trapezoid_tab)
        self.label_15.setGeometry(QtCore.QRect(140, 60, 52, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.trapezoid_tab)
        self.label_16.setGeometry(QtCore.QRect(140, 120, 52, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.trapezoid_tab)
        self.label_17.setGeometry(QtCore.QRect(140, 180, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.answer_section6 = QtWidgets.QLabel(self.trapezoid_tab)
        self.answer_section6.setGeometry(QtCore.QRect(70, 270, 371, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.answer_section6.setFont(font)
        self.answer_section6.setWordWrap(True)
        self.answer_section6.setObjectName("answer_section6")
        self.submit_button6 = QtWidgets.QPushButton(self.trapezoid_tab)
        self.submit_button6.setGeometry(QtCore.QRect(70, 460, 84, 25))
        self.submit_button6.setObjectName("submit_button6")
        self.submit_button6.clicked.connect(self.submit_trapezoid)
        self.clear_button6 = QtWidgets.QPushButton(self.trapezoid_tab)
        self.clear_button6.setGeometry(QtCore.QRect(360, 460, 84, 25))
        self.clear_button6.setObjectName("clear_button6")
        self.clear_button6.clicked.connect(self.clear_trapezoid)
        self.height = QtWidgets.QLineEdit(self.trapezoid_tab)
        self.height.setGeometry(QtCore.QRect(260, 180, 104, 21))
        self.height.setObjectName("height")
        self.base1 = QtWidgets.QLineEdit(self.trapezoid_tab)
        self.base1.setGeometry(QtCore.QRect(260, 60, 104, 21))
        self.base1.setObjectName("base1")
        self.base2 = QtWidgets.QLineEdit(self.trapezoid_tab)
        self.base2.setGeometry(QtCore.QRect(260, 120, 104, 21))
        self.base2.setObjectName("base2")
        self.tabWidget.addTab(self.trapezoid_tab, "")
        self.regular_shape_tab = QtWidgets.QWidget()
        self.regular_shape_tab.setObjectName("regular_shape_tab")
        self.submit_button7 = QtWidgets.QPushButton(self.regular_shape_tab)
        self.submit_button7.setGeometry(QtCore.QRect(70, 460, 84, 25))
        self.submit_button7.setObjectName("submit_button7")
        self.submit_button7.clicked.connect(self.submit_regular)
        self.clear_button7 = QtWidgets.QPushButton(self.regular_shape_tab)
        self.clear_button7.setGeometry(QtCore.QRect(360, 460, 84, 25))
        self.clear_button7.setObjectName("clear_button7")
        self.clear_button7.clicked.connect(self.clear_regular)
        self.label_14 = QtWidgets.QLabel(self.regular_shape_tab)
        self.label_14.setGeometry(QtCore.QRect(80, 50, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_20 = QtWidgets.QLabel(self.regular_shape_tab)
        self.label_20.setGeometry(QtCore.QRect(80, 190, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.regular_side = QtWidgets.QLineEdit(self.regular_shape_tab)
        self.regular_side.setGeometry(QtCore.QRect(280, 50, 111, 21))
        self.regular_side.setObjectName("regular_side")
        self.side_number = QtWidgets.QLineEdit(self.regular_shape_tab)
        self.side_number.setGeometry(QtCore.QRect(280, 190, 111, 21))
        self.side_number.setObjectName("side_number")
        self.answer_section7 = QtWidgets.QLabel(self.regular_shape_tab)
        self.answer_section7.setGeometry(QtCore.QRect(70, 270, 371, 151))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.answer_section7.setFont(font)
        self.answer_section7.setWordWrap(True)
        self.answer_section7.setObjectName("answer_section7")
        self.tabWidget.addTab(self.regular_shape_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 509, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Geometry Helper"))
        self.label.setText(_translate("MainWindow", "Radius"))
        self.answer_section.setText(_translate("MainWindow", "Enter the Radius and we will give you the Circumfrence and the Area."))
        self.submit_button.setText(_translate("MainWindow", "Submit"))
        self.clear_button.setText(_translate("MainWindow", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.circle_tab), _translate("MainWindow", "Circle"))
        self.label_2.setText(_translate("MainWindow", "Minor Axis"))
        self.label_3.setText(_translate("MainWindow", "Major Axis"))
        self.answer_section2.setText(_translate("MainWindow", "Enter the Minor Axis and the Major Axis and we will give you the area and approximate the perimeter."))
        self.submit_button2.setText(_translate("MainWindow", "Submit"))
        self.clear_button2.setText(_translate("MainWindow", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.elipse_tab), _translate("MainWindow", "Elipse"))
        self.label_5.setText(_translate("MainWindow", "Side 1"))
        self.label_6.setText(_translate("MainWindow", "Side 2"))
        self.label_7.setText(_translate("MainWindow", "Side 3"))
        self.label_8.setText(_translate("MainWindow", "Angle 1"))
        self.label_9.setText(_translate("MainWindow", "Angle 2"))
        self.label_10.setText(_translate("MainWindow", "Angle 3"))
        self.submit_button3.setText(_translate("MainWindow", "Submit"))
        self.clear_button3.setText(_translate("MainWindow", "Clear"))
        self.label_11.setText(_translate("MainWindow", "Enter 3 things and we will fill in the rest. One of the 3 things must be a side. All inputs should be greater than 0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.triangle_tab), _translate("MainWindow", "Triangle"))
        self.submit_button4.setText(_translate("MainWindow", "Submit"))
        self.clear_button4.setText(_translate("MainWindow", "Clear"))
        self.label_12.setText(_translate("MainWindow", "Side length"))
        self.answer_section4.setText(_translate("MainWindow", "Enter a side length and we will give you the perimeter and the area."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.square_tab), _translate("MainWindow", "Square"))
        self.label_4.setText(_translate("MainWindow", "Side length 1"))
        self.label_13.setText(_translate("MainWindow", "Side length 2"))
        self.answer_section5.setText(_translate("MainWindow", "Enter 2 side lengths and we will give you the Perimeter and the Area"))
        self.submit_button5.setText(_translate("MainWindow", "Submit"))
        self.clear_button5.setText(_translate("MainWindow", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rectangle_tab), _translate("MainWindow", "Rectangle"))
        self.label_15.setText(_translate("MainWindow", "Base 1"))
        self.label_16.setText(_translate("MainWindow", "Base 2"))
        self.label_17.setText(_translate("MainWindow", "Height"))
        self.answer_section6.setText(_translate("MainWindow", "Enter the height and the 2 bases and we will generate the area"))
        self.submit_button6.setText(_translate("MainWindow", "Submit"))
        self.clear_button6.setText(_translate("MainWindow", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.trapezoid_tab), _translate("MainWindow", "Trapezoid"))
        self.submit_button7.setText(_translate("MainWindow", "Submit"))
        self.clear_button7.setText(_translate("MainWindow", "Clear"))
        self.label_14.setText(_translate("MainWindow", "Side Length"))
        self.label_20.setText(_translate("MainWindow", "Number of Sides"))
        self.answer_section7.setText(_translate("MainWindow", "Enter the Side Length and the Number of Sides, and we will generate the Area and the Perimeter of any Regular Shape. If side number is not an integer, it will be rounded down."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.regular_shape_tab), _translate("MainWindow", "Regular Shape"))

    def submit_regular(self):
        _translate = QtCore.QCoreApplication.translate
        if self.regular_side.text().isdigit() == True and self.side_number.text().isdigit() == True:
            side = int(self.regular_side.text())
            side_number = float(self.side_number.text())
            if side > 2 and side_number > 0:
                regular_area = s.regularArea(side, side_number)
                regular_perimeter = s.regularPerimeter(side, side_number)
                self.answer_section7.setText(_translate("MainWindow", "Area          {:.2f}\nPerimeter     {:.2f}".format(regular_area, regular_perimeter)))
            else:
                self.answer_section7.setText(_translate("MainWindow", "Double check your inputs. Make sure your inputs are greater than zero."))
        else:
            self.answer_section7.setText(_translate("MainWindow", "Make sure your inputs are integers."))
    def submit_trapezoid(self):
        _translate = QtCore.QCoreApplication.translate
        if self.base1.text().isdigit() == True and self.base2.text().isdigit() == True and self.height.text().isdigit() == True:
            base1 = float(self.base1.text())
            base2 = float(self.base2.text())
            height = float(self.height.text())
            if base1 > 0 and base2 > 0 and height > 0:
                trapezoid_area = s.trapezoid(base1, base2, height)
                self.answer_section6.setText(_translate("MainWindow", "Area          {:.2f}".format(trapezoid_area)))
            else:
                self.answer_section6.setText(_translate("MainWindow", "Double check your inputs. Make sure your inputs are greater than zero."))
        else:
            self.answer_section6.setText(_translate("MainWindow", "Make sure your inputs are integers."))
    def submit_elipse(self):
        _translate = QtCore.QCoreApplication.translate
        if self.minor_axis.text().isdigit() == True and self.major_axis.text().isdigit() == True:
            minor_axis = float(self.minor_axis.text())
            major_axis = float(self.major_axis.text())
            if minor_axis > 0 and major_axis > minor_axis:
                elipse_area = s.elipseArea(minor_axis, major_axis)
                elipse_perimeter = s.elipsePerimeter(minor_axis, major_axis)
                self.answer_section2.setText(_translate("MainWindow", "Area          {:.2f}\nPerimeter     {:.2f}".format(elipse_area, elipse_perimeter)))
            else:
                self.answer_section2.setText(_translate("MainWindow", "Double check your inputs. Make sure your inputs are greater than zero, and that the Minor Axis is smaller than the Major Axis."))
        else:
            self.answer_section2.setText(_translate("MainWindow", "Make sure your inputs are integers."))
    def submit_rectangle(self):
        _translate = QtCore.QCoreApplication.translate
        if self.rectangle_side1.text().isdigit() == True and self.rectangle_side2.text().isdigit() == True:
            length = float(self.rectangle_side1.text())
            width = float(self.rectangle_side2.text())
            if length > 0 and width > 0:
                rectangle_area = s.rectangleArea(length, width)
                rectangle_perimeter = s.rectanglePerimeter(length, width)
                self.answer_section5.setText(_translate("MainWindow", "Area          {:.2f}\nPerimeter     {:.2f}".format(rectangle_area, rectangle_perimeter)))
            else:
                self.answer_section5.setText(_translate("MainWindow", "Double check your inputs. Make sure your inputs are greater than zero."))
        else:
            self.answer_section5.setText(_translate("MainWindow", "Make sure your inputs are integers."))
    def submit_square(self):
        _translate = QtCore.QCoreApplication.translate
        if self.square_side.text().isdigit() == True:
            base = float(self.square_side.text())
            
            if base > 0:
                square_area = s.rectangleArea(base, base)
                square_perimeter = s.rectanglePerimeter(base, base)
                self.answer_section4.setText(_translate("MainWindow", "Area          {:.2f}\nPerimeter     {:.2f}".format(square_area, square_perimeter)))
            else:
                self.answer_section4.setText(_translate("MainWindow", "Double check your input. Make sure your input is greater than zero."))
        else:
            self.answer_section4.setText(_translate("MainWindow", "Make sure your input is a number."))
    def submit_circle(self):
        _translate = QtCore.QCoreApplication.translate
        if self.radius.text().isdigit() == True:
            radius = float(self.radius.text())
            
            if radius > 0:
                circle_area = s.circleArea(radius)
                circle_perimeter = s.circlePerimeter(radius)
                self.answer_section.setText(_translate("MainWindow", "Area          {:.2f}\nPerimeter     {:.2f}".format(circle_area, circle_perimeter)))
            else:
                self.answer_section.setText(_translate("MainWindow", "Double check your input. Make sure your input is greater than zero."))
        else:
            self.answer_section.setText(_translate("MainWindow", "Make sure your input is an integer."))
    def submit_triangle(self):
        _translate = QtCore.QCoreApplication.translate
        sideList = [0,0,0]
        angleList = [0,0,0]
        sideCounter = 0
        angleCounter = 0
        if self.side1.text().isdigit() == True:
            sideList[0] = float(self.side1.text())
            sideCounter += 1
        if self.side2.text().isdigit() == True:
            sideList[1] = float(self.side2.text())
            sideCounter += 1
        if self.side3.text().isdigit() == True:
            sideList[2] = float(self.side3.text())
            sideCounter += 1
        if self.angle1.text().isdigit() == True:
            angleList[0] = float(self.angle1.text())
            angleCounter += 1
        if self.angle2.text().isdigit() == True:
            angleList[1] = float(self.angle2.text())
            angleCounter += 1
        if self.angle3.text().isdigit() == True:
            angleList[2] = float(self.angle3.text())
            angleCounter += 1
        if sideCounter >= 1 and (angleCounter + sideCounter) == 3:
            if sideCounter == 1:
                for i in range(3):
                    if angleList[i] <= 0:
                        angleList[i] = 180 - angleList[i - 1] - angleList[i - 2]
                        
                for i in range(3):
                    if sideList[i] > 0:
                        sideList[i - 1] = s.lawOfSinesSide(sideList[i], angleList[i], angleList[i - 1])
                        sideList[i - 2] = s.lawOfSinesSide(sideList[i], angleList[i], angleList[i - 2])
                        
            if sideCounter == 2:
                for i in range(3):
                    if angleList[i] > 0 and sideList[i] <= 0:
                        sideList[i] = s.lawOfCosines(angleList[i], sideList[i - 1], sideList[i - 2])
                        if angleList[i - 1] <= 0:
                            angleList[i - 1] = s.lawOfSinesAngle(angleList[i], sideList[i], sideList[i - 1])
                        if angleList[i - 2] <= 0:
                            angleList[i - 2] = s.lawOfSinesAngle(angleList[i], sideList[i], sideList[i - 2])
                    elif angleList[i] > 0 and sideList[i] > 0 and sideList[i - 1] <= 0:
                        if angleList[i - 2] <= 0:
                            angleList[i - 2] = s.lawOfSinesAngle(angleList[i], sideList[i], sideList[i - 2])
                        if angleList[i - 1] <= 0:
                            angleList[i - 1] = 180 - angleList[i] - angleList[i - 2]
                        sideList[i - 1] = s.lawOfCosines(angleList[i - 1], sideList[i], sideList[i - 2])
                    elif angleList[i] > 0 and sideList[i] > 0 and sideList[i - 2] <= 0:
                        if angleList[i - 1] <= 0:
                            angleList[i - 1] = s.lawOfSinesAngle(angleList[i], sideList[i], sideList[i - 1])
                        if angleList[i - 2] <= 0:
                            angleList[i - 2] = 180 - angleList[i] - angleList[i - 1]
                        sideList[i - 2] = s.lawOfCosines(angleList[i - 2], sideList[i], sideList[i - 1])
            
            if sideCounter == 3:
                for i in range(3):
                    if angleList[i] <= 0:
                        angleList[i] = s.lawOfCosinesAngle(sideList[i], sideList[i - 1], sideList[i - 2])
            triangle_area = s.triangleArea(sideList[0], sideList[1], sideList[2])
            triangle_perimeter = sideList[0] + sideList[1] + sideList[2]
            self.label_11.setText(_translate("MainWindow", "Area:            {:.2f}\nPerimeter:      {:.2f}".format(triangle_area, triangle_perimeter)))
            self.angle1.setText(_translate("MainWindow", "{:.2f}".format(angleList[0])))            
            self.angle2.setText(_translate("MainWindow", "{:.2f}".format(angleList[1])))
            self.angle3.setText(_translate("MainWindow", "{:.2f}".format(angleList[2])))
            self.side1.setText(_translate("MainWindow", "{:.2f}".format(sideList[0]))) 
            self.side2.setText(_translate("MainWindow", "{:.2f}".format(sideList[1])))
            self.side3.setText(_translate("MainWindow", "{:.2f}".format(sideList[2])))
        else:
            self.label_11.setText(_translate("MainWindow", "Double check your inputs. Make sure they're all integers that are greater than zero."))
    def clear_triangle(self):
        _translate = QtCore.QCoreApplication.translate
        self.angle1.setText(_translate("MainWindow", ""))            
        self.angle2.setText(_translate("MainWindow", ""))
        self.angle3.setText(_translate("MainWindow", ""))
        self.side1.setText(_translate("MainWindow", "")) 
        self.side2.setText(_translate("MainWindow", ""))
        self.side3.setText(_translate("MainWindow", ""))
        self.label_11.setText(_translate("MainWindow", "Enter 3 things and we will fill in the rest. One of the 3 things must be a side. All inputs should be greater than 0"))            
    def clear_elipse(self):
        _translate = QtCore.QCoreApplication.translate
        self.minor_axis.setText(_translate("MainWindow", ""))
        self.major_axis.setText(_translate("MainWindow", ""))
        self.answer_section2.setText(_translate("MainWindow", "Enter the Minor Axis and the Major Axis and we will give you the area and approximate the perimeter."))
    def clear_rectangle(self):
        _translate = QtCore.QCoreApplication.translate
        self.rectangle_side1.setText(_translate("MainWindow", ""))
        self.rectangle_side2.setText(_translate("MainWindow", ""))
        self.answer_section5.setText(_translate("MainWindow", "Enter 2 side lengths and we will give you the Perimeter and the Area"))
    def clear_square(self):
        _translate = QtCore.QCoreApplication.translate
        self.square_side.setText(_translate("MainWindow", ""))
        self.answer_section4.setText(_translate("MainWindow", "Enter a side length and we will give you the perimeter and the area."))
    def clear_circle(self):
        _translate = QtCore.QCoreApplication.translate
        self.radius.setText(_translate("MainWindow", ""))
        self.answer_section.setText(_translate("MainWindow", "Enter the Radius and we will give you the Circumfrence and the Area."))
    def clear_trapezoid(self):
        _translate = QtCore.QCoreApplication.translate
        self.base1.setText(_translate("MainWindow",""))
        self.base2.setText(_translate("MainWindow",""))
        self.height.setText(_translate("MainWindow",""))
        self.answer_section6.setText(_translate("MainWindow", "Enter the height and the 2 bases and we will generate the area"))
    def clear_regular(self):
        _translate = QtCore.QCoreApplication.translate
        self.side_number.setText(_translate("MainWindow",""))
        self.regular_side.setText(_translate("MainWindow",""))
        self.answer_section7.setText(_translate("MainWindow", "Enter the Side Length and the Number of Sides, and we will generate the Area and the Perimeter of any Regular Shape. If Side Number is not an integer, it will be rounded down."))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
